# Generated by Django 5.0.7 on 2024-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FraudDetectionApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "married",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                ("dependents", models.CharField(max_length=10)),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("Graduate", "Graduate"),
                            ("Not Graduate", "Not Graduate"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "self_employed",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                ("applicant_income", models.IntegerField()),
                ("coapplicant_income", models.IntegerField()),
                ("loan_amount", models.IntegerField()),
                ("loan_amount_term", models.IntegerField()),
                ("credit_history", models.FloatField()),
                (
                    "property_area",
                    models.IntegerField(
                        choices=[
                            ("Urban", "Urban"),
                            ("Semiurban", "Semiurban"),
                            ("Rural", "Rural"),
                        ]
                    ),
                ),
            ],
        ),
    ]
