# Generated by Django 5.0.7 on 2024-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FraudDetectionApp", "0002_loanapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="property_area",
            field=models.CharField(
                choices=[
                    ("Urban", "Urban"),
                    ("Semiurban", "Semiurban"),
                    ("Rural", "Rural"),
                ],
                max_length=20,
            ),
        ),
    ]
