# Generated by Django 5.0.7 on 2024-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FraudDetectionApp", "0003_alter_loanapplication_property_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardFraud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("pay_0", models.IntegerField()),
                ("pay_2", models.IntegerField()),
                ("pay_3", models.IntegerField()),
                ("pay_4", models.IntegerField()),
                ("pay_5", models.IntegerField()),
                ("pay_6", models.IntegerField()),
                ("bill_amt1", models.FloatField()),
                ("bill_amt2", models.FloatField()),
                ("bill_amt3", models.FloatField()),
                ("bill_amt4", models.FloatField()),
                ("bill_amt5", models.FloatField()),
                ("bill_amt6", models.FloatField()),
                ("loan_status", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
