# Generated by Django 5.0.7 on 2024-07-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FraudDetectionApp", "0005_goldpriceprediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitcoinPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("adj_close", models.FloatField()),
                ("volume", models.FloatField()),
                ("coin", models.FloatField()),
                ("year", models.IntegerField()),
                ("prediction", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
